### ISSUE TITLE
As an author, posts I create can link to images.

### ISSUE THREAD

**Issue by nshillin** [CMPUT404W17T06/CMPUT404-project#2]

**Comment by nshillin** [comment]
I'm not sure if this is any image or just images that users have uploaded. If it's any image, that can be done with markdown at the moment

**Comment by kuzi117** [comment]
Their stories are too vague... I think the markdown is a good interpretation of it. If Josh wants to argue about it.. We can argue with Hindle. I'll reassign to you and call it done.

**Comment by kuzi117** [comment]
For submission: verified, assuming through markdown is ok. (PS, I thought it would just make a link to an image, it actually brings the image into the post. Very nice :+1: )
